name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r awscon/requirements.txt
    - name: Lint check the code
      run: |
        pip install black
        black --check .
    - name: Strict typing check
      run: |
        pip install mypy
        mypy awscon/*.py --ignore-missing-imports
    - name: Bandit code security check
      run: |
        pip install bandit
        bandit awswcon/*.py -ll
    - name: Dependencies security check
      run: |
        pip install safety
        safety check -r awscon/requirements.txt
